# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /

# 应用基础配置
app:
  # 应用基础信息
  name: Candy AI
  version: 1.0.1
  # 服务器地址配置
  server:
    protocol: http
    host: localhost
    port: 8080
    context-path: /
  # 构建完整的服务器URL
  base-url: ${app.server.protocol}://${app.server.host}:${app.server.port}${app.server.context-path}

# 开发环境配置
spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/candy_ai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: "123456"
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url: 
        username: 
        password: 
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter: 
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  # redis 配置
  data:
    redis:
      # 地址
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password: "123456"
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

# Candy AI 缓存配置
candy:
  cache:
    enabled: false  # 开发环境禁用缓存，使用真实数据
  # OAuth 第三方登录配置
  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
      client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
      redirect-uri: ${app.base-url}/auth/oauth/callback/google
    github:
      client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
      client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
      redirect-uri: ${app.base-url}/auth/oauth/callback/github
    discord:
      client-id: ${DISCORD_CLIENT_ID:your-discord-client-id}
      client-secret: ${DISCORD_CLIENT_SECRET:your-discord-client-secret}
      redirect-uri: ${app.base-url}/auth/oauth/callback/discord
    apple:
      client-id: ${APPLE_CLIENT_ID:your-apple-client-id}
      client-secret: ${APPLE_CLIENT_SECRET:your-apple-client-secret}
      redirect-uri: ${app.base-url}/auth/oauth/callback/apple
    facebook:
      client-id: ${FACEBOOK_CLIENT_ID:your-facebook-client-id}
      client-secret: ${FACEBOOK_CLIENT_SECRET:your-facebook-client-secret}
      redirect-uri: ${app.base-url}/auth/oauth/callback/facebook

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
    com.ruoyi.system.mapper: debug  # 开发环境启用SQL日志

# 开发环境配置
ruoyi:
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
  # 开发环境禁用验证码
  captchaEnabled: false
  # 数据库表前缀配置
  tablePrefix:
    ruoyi: ""        # RuoYi 系统表无前缀（保持原样）
    candy: candy_    # Candy AI 业务表前缀

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true 